/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateIndexApiRequest : Create index request object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateIndexApiRequest {
    #[serde(rename = "index_name")]
    pub index_name: String,
    #[serde(rename = "schema")]
    pub schema: Vec<models::SchemaField>,
    #[serde(rename = "similarity", skip_serializing_if = "Option::is_none")]
    pub similarity: Option<models::SimilarityType>,
    #[serde(rename = "tokenizer", skip_serializing_if = "Option::is_none")]
    pub tokenizer: Option<models::TokenizerType>,
    #[serde(rename = "synonyms")]
    pub synonyms: Vec<models::Synonym>,
}

impl CreateIndexApiRequest {
    /// Create index request object
    pub fn new(
        index_name: String,
        schema: Vec<models::SchemaField>,
        synonyms: Vec<models::Synonym>,
    ) -> CreateIndexApiRequest {
        CreateIndexApiRequest {
            index_name,
            schema,
            similarity: None,
            tokenizer: None,
            synonyms,
        }
    }
}
