/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DistanceUnit : DistanceUnit defines the unit for distance calculation: kilometers or miles.
/// DistanceUnit defines the unit for distance calculation: kilometers or miles.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DistanceUnit {
    #[serde(rename = "Kilometers")]
    Kilometers,
    #[serde(rename = "Miles")]
    Miles,

}

impl std::fmt::Display for DistanceUnit {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Kilometers => write!(f, "Kilometers"),
            Self::Miles => write!(f, "Miles"),
        }
    }
}

impl Default for DistanceUnit {
    fn default() -> DistanceUnit {
        Self::Kilometers
    }
}

