/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValueOneOf : Boolean value
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetValueOneOf {
    /// Boolean value
    #[serde(rename = "Bool")]
    pub bool: bool,
}

impl FacetValueOneOf {
    /// Boolean value
    pub fn new(bool: bool) -> FacetValueOneOf {
        FacetValueOneOf {
            bool,
        }
    }
}

