/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValueOneOf13 : String set value
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetValueOneOf13 {
    /// String set value
    #[serde(rename = "StringSet")]
    pub string_set: Vec<String>,
}

impl FacetValueOneOf13 {
    /// String set value
    pub fn new(string_set: Vec<String>) -> FacetValueOneOf13 {
        FacetValueOneOf13 {
            string_set,
        }
    }
}

