/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValueOneOf9 : Unix timestamp: the number of seconds since 1 January 1970
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetValueOneOf9 {
    /// Unix timestamp: the number of seconds since 1 January 1970
    #[serde(rename = "Timestamp")]
    pub timestamp: i64,
}

impl FacetValueOneOf9 {
    /// Unix timestamp: the number of seconds since 1 January 1970
    pub fn new(timestamp: i64) -> FacetValueOneOf9 {
        FacetValueOneOf9 {
            timestamp,
        }
    }
}

