/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf13Point : Point proximity range filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf13Point {
    /// field name
    #[serde(rename = "field")]
    pub field: String,
    /// filter: base point (latitude/lat, longitude/lon), proximity range start, proximity range end, distance unit
    #[serde(rename = "filter")]
    pub filter: Vec<serde_json::Value>,
}

impl FacetFilterOneOf13Point {
    /// Point proximity range filter
    pub fn new(field: String, filter: Vec<serde_json::Value>) -> FacetFilterOneOf13Point {
        FacetFilterOneOf13Point { field, filter }
    }
}
