/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf12StringSet : StringSet filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf12StringSet {
    /// field name
    #[serde(rename = "field")]
    pub field: String,
    /// filter: array of facet string values
    #[serde(rename = "filter")]
    pub filter: Vec<String>,
}

impl FacetFilterOneOf12StringSet {
    /// StringSet filter
    pub fn new(field: String, filter: Vec<String>) -> FacetFilterOneOf12StringSet {
        FacetFilterOneOf12StringSet { field, filter }
    }
}
