/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf8Timestamp : Timestamp range filter, Unix timestamp: the number of seconds since 1 January 1970
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf8Timestamp {
    /// field name
    #[serde(rename = "field")]
    pub field: String,
    /// filter: range start, range end
    #[serde(rename = "filter")]
    pub filter: Box<models::RangeI64>,
}

impl FacetFilterOneOf8Timestamp {
    /// Timestamp range filter, Unix timestamp: the number of seconds since 1 January 1970
    pub fn new(field: String, filter: models::RangeI64) -> FacetFilterOneOf8Timestamp {
        FacetFilterOneOf8Timestamp {
            field,
            filter: Box::new(filter),
        }
    }
}

