/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf10 : F64 range filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf10 {
    #[serde(rename = "F64")]
    pub f64: Box<models::FacetFilterOneOf10F64>,
}

impl FacetFilterOneOf10 {
    /// F64 range filter
    pub fn new(f64: models::FacetFilterOneOf10F64) -> FacetFilterOneOf10 {
        FacetFilterOneOf10 { f64: Box::new(f64) }
    }
}
