/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValueOneOf12 : String value
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetValueOneOf12 {
    /// String value
    #[serde(rename = "String")]
    pub string: String,
}

impl FacetValueOneOf12 {
    /// String value
    pub fn new(string: String) -> FacetValueOneOf12 {
        FacetValueOneOf12 { string }
    }
}
