/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValueOneOf3 : Unsigned 32-bit integer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetValueOneOf3 {
    /// Unsigned 32-bit integer
    #[serde(rename = "U32")]
    pub u32: i32,
}

impl FacetValueOneOf3 {
    /// Unsigned 32-bit integer
    pub fn new(u32: i32) -> FacetValueOneOf3 {
        FacetValueOneOf3 { u32 }
    }
}
