/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValueOneOf8 : Signed 64-bit integer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetValueOneOf8 {
    /// Signed 64-bit integer
    #[serde(rename = "I64")]
    pub i64: i64,
}

impl FacetValueOneOf8 {
    /// Signed 64-bit integer
    pub fn new(i64: i64) -> FacetValueOneOf8 {
        FacetValueOneOf8 {
            i64,
        }
    }
}

