/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf3 : U64 range filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf3 {
    #[serde(rename = "U64")]
    pub u64: Box<models::FacetFilterOneOf3U64>,
}

impl FacetFilterOneOf3 {
    /// U64 range filter
    pub fn new(u64: models::FacetFilterOneOf3U64) -> FacetFilterOneOf3 {
        FacetFilterOneOf3 {
            u64: Box::new(u64),
        }
    }
}

