/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf1 : U16 range filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf1 {
    #[serde(rename = "U16")]
    pub u16: Box<models::FacetFilterOneOf1U16>,
}

impl FacetFilterOneOf1 {
    /// U16 range filter
    pub fn new(u16: models::FacetFilterOneOf1U16) -> FacetFilterOneOf1 {
        FacetFilterOneOf1 {
            u16: Box::new(u16),
        }
    }
}

