/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf5 : I16 range filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf5 {
    #[serde(rename = "I16")]
    pub i16: Box<models::FacetFilterOneOf5I16>,
}

impl FacetFilterOneOf5 {
    /// I16 range filter
    pub fn new(i16: models::FacetFilterOneOf5I16) -> FacetFilterOneOf5 {
        FacetFilterOneOf5 { i16: Box::new(i16) }
    }
}
