/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf13 : Point proximity range filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf13 {
    #[serde(rename = "Point")]
    pub point: Box<models::FacetFilterOneOf13Point>,
}

impl FacetFilterOneOf13 {
    /// Point proximity range filter
    pub fn new(point: models::FacetFilterOneOf13Point) -> FacetFilterOneOf13 {
        FacetFilterOneOf13 {
            point: Box::new(point),
        }
    }
}

