/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf9F32 : F32 range filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf9F32 {
    /// field name
    #[serde(rename = "field")]
    pub field: String,
    /// filter: range start, range end
    #[serde(rename = "filter")]
    pub filter: Box<models::RangeF32>,
}

impl FacetFilterOneOf9F32 {
    /// F32 range filter
    pub fn new(field: String, filter: models::RangeF32) -> FacetFilterOneOf9F32 {
        FacetFilterOneOf9F32 {
            field,
            filter: Box::new(filter),
        }
    }
}
