/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValue : FacetValue: Facet field value types
/// FacetValue: Facet field value types
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FacetValue {
    FacetValueOneOf(Box<models::FacetValueOneOf>),
    FacetValueOneOf1(Box<models::FacetValueOneOf1>),
    FacetValueOneOf2(Box<models::FacetValueOneOf2>),
    FacetValueOneOf3(Box<models::FacetValueOneOf3>),
    FacetValueOneOf4(Box<models::FacetValueOneOf4>),
    FacetValueOneOf5(Box<models::FacetValueOneOf5>),
    FacetValueOneOf6(Box<models::FacetValueOneOf6>),
    FacetValueOneOf7(Box<models::FacetValueOneOf7>),
    FacetValueOneOf8(Box<models::FacetValueOneOf8>),
    FacetValueOneOf9(Box<models::FacetValueOneOf9>),
    FacetValueOneOf10(Box<models::FacetValueOneOf10>),
    FacetValueOneOf11(Box<models::FacetValueOneOf11>),
    FacetValueOneOf12(Box<models::FacetValueOneOf12>),
    FacetValueOneOf13(Box<models::FacetValueOneOf13>),
    FacetValueOneOf14(Box<models::FacetValueOneOf14>),
    /// No value
    String(String),
}

impl Default for FacetValue {
    fn default() -> Self {
        Self::FacetValueOneOf(Default::default())
    }
}
