/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValueOneOf11 : 64-bit floating point number
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetValueOneOf11 {
    /// 64-bit floating point number
    #[serde(rename = "F64")]
    pub f64: f64,
}

impl FacetValueOneOf11 {
    /// 64-bit floating point number
    pub fn new(f64: f64) -> FacetValueOneOf11 {
        FacetValueOneOf11 {
            f64,
        }
    }
}

