/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilter : FacetFilter: either numerical range facet filter (range start/end) or string facet filter (vector of strings) at least one (boolean OR) must match.
/// FacetFilter: either numerical range facet filter (range start/end) or string facet filter (vector of strings) at least one (boolean OR) must match.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FacetFilter {
    FacetFilterOneOf(Box<models::FacetFilterOneOf>),
    FacetFilterOneOf1(Box<models::FacetFilterOneOf1>),
    FacetFilterOneOf2(Box<models::FacetFilterOneOf2>),
    FacetFilterOneOf3(Box<models::FacetFilterOneOf3>),
    FacetFilterOneOf4(Box<models::FacetFilterOneOf4>),
    FacetFilterOneOf5(Box<models::FacetFilterOneOf5>),
    FacetFilterOneOf6(Box<models::FacetFilterOneOf6>),
    FacetFilterOneOf7(Box<models::FacetFilterOneOf7>),
    FacetFilterOneOf8(Box<models::FacetFilterOneOf8>),
    FacetFilterOneOf9(Box<models::FacetFilterOneOf9>),
    FacetFilterOneOf10(Box<models::FacetFilterOneOf10>),
    FacetFilterOneOf11(Box<models::FacetFilterOneOf11>),
    FacetFilterOneOf12(Box<models::FacetFilterOneOf12>),
    FacetFilterOneOf13(Box<models::FacetFilterOneOf13>),
}

impl Default for FacetFilter {
    fn default() -> Self {
        Self::FacetFilterOneOf(Default::default())
    }
}
