/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValueOneOf4 : Unsigned 64-bit integer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetValueOneOf4 {
    /// Unsigned 64-bit integer
    #[serde(rename = "U64")]
    pub u64: i64,
}

impl FacetValueOneOf4 {
    /// Unsigned 64-bit integer
    pub fn new(u64: i64) -> FacetValueOneOf4 {
        FacetValueOneOf4 { u64 }
    }
}
