/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf12 : StringSet filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf12 {
    #[serde(rename = "StringSet")]
    pub string_set: Box<models::FacetFilterOneOf12StringSet>,
}

impl FacetFilterOneOf12 {
    /// StringSet filter
    pub fn new(string_set: models::FacetFilterOneOf12StringSet) -> FacetFilterOneOf12 {
        FacetFilterOneOf12 {
            string_set: Box::new(string_set),
        }
    }
}
