/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf8 : Timestamp range filter, Unix timestamp: the number of seconds since 1 January 1970
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf8 {
    #[serde(rename = "Timestamp")]
    pub timestamp: Box<models::FacetFilterOneOf8Timestamp>,
}

impl FacetFilterOneOf8 {
    /// Timestamp range filter, Unix timestamp: the number of seconds since 1 January 1970
    pub fn new(timestamp: models::FacetFilterOneOf8Timestamp) -> FacetFilterOneOf8 {
        FacetFilterOneOf8 {
            timestamp: Box::new(timestamp),
        }
    }
}
