/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValueOneOf5 : Signed 8-bit integer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetValueOneOf5 {
    /// Signed 8-bit integer
    #[serde(rename = "I8")]
    pub i8: i32,
}

impl FacetValueOneOf5 {
    /// Signed 8-bit integer
    pub fn new(i8: i32) -> FacetValueOneOf5 {
        FacetValueOneOf5 { i8 }
    }
}
