/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValueOneOf2 : Unsigned 16-bit integer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetValueOneOf2 {
    /// Unsigned 16-bit integer
    #[serde(rename = "U16")]
    pub u16: i32,
}

impl FacetValueOneOf2 {
    /// Unsigned 16-bit integer
    pub fn new(u16: i32) -> FacetValueOneOf2 {
        FacetValueOneOf2 {
            u16,
        }
    }
}

