/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf11 : String filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf11 {
    #[serde(rename = "String")]
    pub string: Box<models::FacetFilterOneOf11String>,
}

impl FacetFilterOneOf11 {
    /// String filter
    pub fn new(string: models::FacetFilterOneOf11String) -> FacetFilterOneOf11 {
        FacetFilterOneOf11 {
            string: Box::new(string),
        }
    }
}
