/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterOneOf6 : I32 range filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetFilterOneOf6 {
    #[serde(rename = "I32")]
    pub i32: Box<models::FacetFilterOneOf6I32>,
}

impl FacetFilterOneOf6 {
    /// I32 range filter
    pub fn new(i32: models::FacetFilterOneOf6I32) -> FacetFilterOneOf6 {
        FacetFilterOneOf6 { i32: Box::new(i32) }
    }
}
