/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetValueOneOf7 : Signed 32-bit integer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetValueOneOf7 {
    /// Signed 32-bit integer
    #[serde(rename = "I32")]
    pub i32: i32,
}

impl FacetValueOneOf7 {
    /// Signed 32-bit integer
    pub fn new(i32: i32) -> FacetValueOneOf7 {
        FacetValueOneOf7 {
            i32,
        }
    }
}

