/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MinMaxFieldJson : MinMaxFieldJson is a JSON representation of the minimum and maximum value of a field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinMaxFieldJson {
    #[serde(rename = "min", deserialize_with = "Option::deserialize")]
    pub min: Option<serde_json::Value>,
    #[serde(rename = "max", deserialize_with = "Option::deserialize")]
    pub max: Option<serde_json::Value>,
}

impl MinMaxFieldJson {
    /// MinMaxFieldJson is a JSON representation of the minimum and maximum value of a field.
    pub fn new(min: Option<serde_json::Value>, max: Option<serde_json::Value>) -> MinMaxFieldJson {
        MinMaxFieldJson { min, max }
    }
}
