/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOf2 : Range segment definition for numerical facet field values of type u32
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOf2 {
    #[serde(rename = "U32")]
    pub u32: Box<models::QueryFacetOneOf2U32>,
}

impl QueryFacetOneOf2 {
    /// Range segment definition for numerical facet field values of type u32
    pub fn new(u32: models::QueryFacetOneOf2U32) -> QueryFacetOneOf2 {
        QueryFacetOneOf2 {
            u32: Box::new(u32),
        }
    }
}

