/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOf1 : Range segment definition for numerical facet field values of type u16
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOf1 {
    #[serde(rename = "U16")]
    pub u16: Box<models::QueryFacetOneOf1U16>,
}

impl QueryFacetOneOf1 {
    /// Range segment definition for numerical facet field values of type u16
    pub fn new(u16: models::QueryFacetOneOf1U16) -> QueryFacetOneOf1 {
        QueryFacetOneOf1 { u16: Box::new(u16) }
    }
}
