/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOf5 : Range segment definition for numerical facet field values of type i16
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOf5 {
    #[serde(rename = "I16")]
    pub i16: Box<models::QueryFacetOneOf5I16>,
}

impl QueryFacetOneOf5 {
    /// Range segment definition for numerical facet field values of type i16
    pub fn new(i16: models::QueryFacetOneOf5I16) -> QueryFacetOneOf5 {
        QueryFacetOneOf5 { i16: Box::new(i16) }
    }
}
