/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOf7 : Range segment definition for numerical facet field values of type i64
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOf7 {
    #[serde(rename = "I64")]
    pub i64: Box<models::QueryFacetOneOf7I64>,
}

impl QueryFacetOneOf7 {
    /// Range segment definition for numerical facet field values of type i64
    pub fn new(i64: models::QueryFacetOneOf7I64) -> QueryFacetOneOf7 {
        QueryFacetOneOf7 { i64: Box::new(i64) }
    }
}
