/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOfU8 : Range segment definition for numerical facet field values of type u8
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOfU8 {
    /// field name
    #[serde(rename = "field")]
    pub field: String,
    /// range type (CountWithinRange,CountBelowRange,CountAboveRange)
    #[serde(rename = "range_type")]
    pub range_type: models::RangeType,
    /// range label, range start
    #[serde(rename = "ranges")]
    pub ranges: Vec<Vec<serde_json::Value>>,
}

impl QueryFacetOneOfU8 {
    /// Range segment definition for numerical facet field values of type u8
    pub fn new(field: String, range_type: models::RangeType, ranges: Vec<Vec<serde_json::Value>>) -> QueryFacetOneOfU8 {
        QueryFacetOneOfU8 {
            field,
            range_type,
            ranges,
        }
    }
}

