/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOf11 : Facet field values of type string
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOf11 {
    #[serde(rename = "String")]
    pub string: Box<models::QueryFacetOneOf11String>,
}

impl QueryFacetOneOf11 {
    /// Facet field values of type string
    pub fn new(string: models::QueryFacetOneOf11String) -> QueryFacetOneOf11 {
        QueryFacetOneOf11 {
            string: Box::new(string),
        }
    }
}

