/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOf13Point : Range segment definition for numerical facet field values of type Point (distance between base of type Point and facet field of type Point)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOf13Point {
    /// field name
    #[serde(rename = "field")]
    pub field: String,
    /// range type (CountWithinRange,CountBelowRange,CountAboveRange)
    #[serde(rename = "range_type")]
    pub range_type: models::RangeType,
    /// range label, range start
    #[serde(rename = "ranges")]
    pub ranges: Vec<Vec<serde_json::Value>>,
    #[serde(rename = "base")]
    pub base: Vec<f64>,
    /// distance unit (kilometers/miles)
    #[serde(rename = "unit")]
    pub unit: models::DistanceUnit,
}

impl QueryFacetOneOf13Point {
    /// Range segment definition for numerical facet field values of type Point (distance between base of type Point and facet field of type Point)
    pub fn new(
        field: String,
        range_type: models::RangeType,
        ranges: Vec<Vec<serde_json::Value>>,
        base: Vec<f64>,
        unit: models::DistanceUnit,
    ) -> QueryFacetOneOf13Point {
        QueryFacetOneOf13Point {
            field,
            range_type,
            ranges,
            base,
            unit,
        }
    }
}
