/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOf10 : Range segment definition for numerical facet field values of type f64
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOf10 {
    #[serde(rename = "F64")]
    pub f64: Box<models::QueryFacetOneOf10F64>,
}

impl QueryFacetOneOf10 {
    /// Range segment definition for numerical facet field values of type f64
    pub fn new(f64: models::QueryFacetOneOf10F64) -> QueryFacetOneOf10 {
        QueryFacetOneOf10 {
            f64: Box::new(f64),
        }
    }
}

