/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOf6 : Range segment definition for numerical facet field values of type i32
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOf6 {
    #[serde(rename = "I32")]
    pub i32: Box<models::QueryFacetOneOf6I32>,
}

impl QueryFacetOneOf6 {
    /// Range segment definition for numerical facet field values of type i32
    pub fn new(i32: models::QueryFacetOneOf6I32) -> QueryFacetOneOf6 {
        QueryFacetOneOf6 {
            i32: Box::new(i32),
        }
    }
}

