/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOf8 : Range segment definition for numerical facet field values of type Unix timestamp
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOf8 {
    #[serde(rename = "Timestamp")]
    pub timestamp: Box<models::QueryFacetOneOf8Timestamp>,
}

impl QueryFacetOneOf8 {
    /// Range segment definition for numerical facet field values of type Unix timestamp
    pub fn new(timestamp: models::QueryFacetOneOf8Timestamp) -> QueryFacetOneOf8 {
        QueryFacetOneOf8 {
            timestamp: Box::new(timestamp),
        }
    }
}

