/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOf3 : Range segment definition for numerical facet field values of type u64
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOf3 {
    #[serde(rename = "U64")]
    pub u64: Box<models::QueryFacetOneOf3U64>,
}

impl QueryFacetOneOf3 {
    /// Range segment definition for numerical facet field values of type u64
    pub fn new(u64: models::QueryFacetOneOf3U64) -> QueryFacetOneOf3 {
        QueryFacetOneOf3 {
            u64: Box::new(u64),
        }
    }
}

