/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacetOneOf13 : Range segment definition for numerical facet field values of type Point (distance between base of type Point and facet field of type Point)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFacetOneOf13 {
    #[serde(rename = "Point")]
    pub point: Box<models::QueryFacetOneOf13Point>,
}

impl QueryFacetOneOf13 {
    /// Range segment definition for numerical facet field values of type Point (distance between base of type Point and facet field of type Point)
    pub fn new(point: models::QueryFacetOneOf13Point) -> QueryFacetOneOf13 {
        QueryFacetOneOf13 {
            point: Box::new(point),
        }
    }
}
