/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryFacet : Defines the query facets: - string facet field values - range segments for numerical facet field values
/// Defines the query facets: - string facet field values - range segments for numerical facet field values
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryFacet {
    QueryFacetOneOf(Box<models::QueryFacetOneOf>),
    QueryFacetOneOf1(Box<models::QueryFacetOneOf1>),
    QueryFacetOneOf2(Box<models::QueryFacetOneOf2>),
    QueryFacetOneOf3(Box<models::QueryFacetOneOf3>),
    QueryFacetOneOf4(Box<models::QueryFacetOneOf4>),
    QueryFacetOneOf5(Box<models::QueryFacetOneOf5>),
    QueryFacetOneOf6(Box<models::QueryFacetOneOf6>),
    QueryFacetOneOf7(Box<models::QueryFacetOneOf7>),
    QueryFacetOneOf8(Box<models::QueryFacetOneOf8>),
    QueryFacetOneOf9(Box<models::QueryFacetOneOf9>),
    QueryFacetOneOf10(Box<models::QueryFacetOneOf10>),
    QueryFacetOneOf11(Box<models::QueryFacetOneOf11>),
    QueryFacetOneOf12(Box<models::QueryFacetOneOf12>),
    QueryFacetOneOf13(Box<models::QueryFacetOneOf13>),
    /// No query facet
    String(String),
}

impl Default for QueryFacet {
    fn default() -> Self {
        Self::QueryFacetOneOf(Default::default())
    }
}
