/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryIndexApiPostRequest : Search request object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryIndexApiPostRequest {
    /// Query string, search operators + - \"\" are recognized.
    #[serde(rename = "query")]
    pub query: String,
    /// Offset of search results to return.
    #[serde(rename = "offset")]
    pub offset: i32,
    /// Number of search results to return.
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<i32>,
    #[serde(rename = "result_type", skip_serializing_if = "Option::is_none")]
    pub result_type: Option<models::ResultType>,
    /// True realtime search: include indexed, but uncommitted documents into search results.
    #[serde(rename = "realtime", skip_serializing_if = "Option::is_none")]
    pub realtime: Option<bool>,
    #[serde(rename = "highlights", skip_serializing_if = "Option::is_none")]
    pub highlights: Option<Vec<models::Highlight>>,
    /// Specify field names where to search at querytime, whereas SchemaField.indexed is set at indextime. If empty then all indexed fields are searched.
    #[serde(rename = "field_filter", skip_serializing_if = "Option::is_none")]
    pub field_filter: Option<Vec<String>>,
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<String>>,
    #[serde(rename = "distance_fields", skip_serializing_if = "Option::is_none")]
    pub distance_fields: Option<Vec<models::DistanceField>>,
    #[serde(rename = "query_facets", skip_serializing_if = "Option::is_none")]
    pub query_facets: Option<Vec<models::QueryFacet>>,
    #[serde(rename = "facet_filter", skip_serializing_if = "Option::is_none")]
    pub facet_filter: Option<Vec<models::FacetFilter>>,
    /// Sort field and order:  Search results are sorted by the specified facet field, either in ascending or descending order. If no sort field is specified, then the search results are sorted by rank in descending order per default. Multiple sort fields are combined by a \"sort by, then sort by\"-method (\"tie-breaking\"-algorithm). The results are sorted by the first field, and only for those results where the first field value is identical (tie) the results are sub-sorted by the second field, until the n-th field value is either not equal or the last field is reached. A special _score field (BM25x), reflecting how relevant the result is for a given search query (phrase match, match in title etc.) can be combined with any of the other sort fields as primary, secondary or n-th search criterium. Sort is only enabled on facet fields that are defined in schema at create_index!  Examples: - result_sort = vec![ResultSort {field: \"price\".into(), order: SortOrder::Descending, base: FacetValue::None},ResultSort {field: \"language\".into(), order: SortOrder::Ascending, base: FacetValue::None}]; - result_sort = vec![ResultSort {field: \"location\".into(),order: SortOrder::Ascending, base: FacetValue::Point(vec![38.8951, -77.0364])}];
    #[serde(rename = "result_sort", skip_serializing_if = "Option::is_none")]
    pub result_sort: Option<Vec<models::ResultSort>>,
    #[serde(rename = "query_type_default", skip_serializing_if = "Option::is_none")]
    pub query_type_default: Option<models::QueryType>,
}

impl QueryIndexApiPostRequest {
    /// Search request object
    pub fn new(query: String, offset: i32) -> QueryIndexApiPostRequest {
        QueryIndexApiPostRequest {
            query,
            offset,
            length: None,
            result_type: None,
            realtime: None,
            highlights: None,
            field_filter: None,
            fields: None,
            distance_fields: None,
            query_facets: None,
            facet_filter: None,
            result_sort: None,
            query_type_default: None,
        }
    }
}
