/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RangeF64 : F64 range filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RangeF64 {
    /// range start
    #[serde(rename = "start")]
    pub start: f64,
    /// range end
    #[serde(rename = "end")]
    pub end: f64,
}

impl RangeF64 {
    /// F64 range filter
    pub fn new(start: f64, end: f64) -> RangeF64 {
        RangeF64 { start, end }
    }
}
