/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RangeU8 : U8 range filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RangeU8 {
    /// range start
    #[serde(rename = "start")]
    pub start: i32,
    /// range end
    #[serde(rename = "end")]
    pub end: i32,
}

impl RangeU8 {
    /// U8 range filter
    pub fn new(start: i32, end: i32) -> RangeU8 {
        RangeU8 { start, end }
    }
}
