/*
 * SeekStorm REST API documentation
 *
 * Search engine library & multi-tenancy server
 *
 * The version of the OpenAPI document: 0.12.11
 * Contact: wolf.garbe@seekstorm.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RangeF32 : F32 range filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RangeF32 {
    /// range start
    #[serde(rename = "start")]
    pub start: f32,
    /// range end
    #[serde(rename = "end")]
    pub end: f32,
}

impl RangeF32 {
    /// F32 range filter
    pub fn new(start: f32, end: f32) -> RangeF32 {
        RangeF32 { start, end }
    }
}
